server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location = / {
    try_files /index.html =404;
  }

  location = /download {
    return 301 /download/;
  }

  location = /download/ {
    try_files /download/index.html =404;
  }

  location / {
    try_files $uri $uri/ $uri.html =404;
  }

  location = /index.html {
    return 301 /;
  }

  location = /privacy.html {
    return 301 /privacy;
  }

  location = /support.html {
    return 301 /support;
  }

  location = /delete-account.html {
    return 301 /delete-account;
  }

  location ~* \.html$ {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";
  }
}
